---
development:
  cloud_name: duskukulx
  api_key: <%= Rails.application.credentials.cloudinary_api[:key]%>
  api_secret: <%= Rails.application.credentials.cloudinary_api[:secret]%>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: duskukulx
  api_key: <%= Rails.application.credentials.cloudinary_api[:key]%>
  api_secret: <%= Rails.application.credentials.cloudinary_api[:secret]%>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: duskukulx
  api_key: <%= Rails.application.credentials.cloudinary_api[:key]%>
  api_secret: <%= Rails.application.credentials.cloudinary_api[:secret]%>
  enhance_image_tag: true
  static_file_support: false
